show databases;
create database SPRINGBOOT character set utf8mb4 collate utf8mb4_general_ci;
use SPRINGBOOT;

DROP TABLE IF EXISTS BOARD;
CREATE TABLE IF NOT EXISTS BOARD (
    BOARD_SEQUENCE INT AUTO_INCREMENT,
    TITLE VARCHAR(50) NOT NULL,
    CONTENTS VARCHAR(1000) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED TINYINT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (BOARD_SEQUENCE)
);

insert into users (user_name) values ('user001');